apiVersion: v1
kind: Service
metadata:
  name: prisma-crud-service
spec:
  selector:
    app: prisma-crud
  ports:
    - protocol: TCP
      name: http-svc
      port: 3000
      targetPort: 3000
  type: LoadBalancer
